<?php
$teams = [
    "prof-dr-lawrence-lowell" => [
        "Prof. Dr. Lawrence Lowell",
        "Executive Director and Co-founder",
        "Prof. Dr. Lawrence Lowell, the Executive Chairman of Community and Entrepreneurial Development Initiative (CEDI Ghana) is a Professor of Business Administration and Dean of International Programmes for St. John of the Cross University, Costa Rica, with PhD in Business Administration. Prof. Lowell is also a Full Professor of International Programmes and \u201cPartner Academician\u201d of Business University of Costa Rica for West Africa, stationed in Nigeria, He is the Director of International Programs for West African Affiliate Centre of Quetzalcoatl University of Veracruz, Mexico. \u003Cbr \/\u003E\u003Cbr \/\u003E Prof. Lowell is a Professional Counseling Psychologist and Guardian Counselor licensed by Ghana Psychology Council, with full Membership of American Psychological Association, Full Membership of International Council of Psychologist and Full Membership of International Association of Applied Psychologist with a 2nd PhD in Psychology.\u003Cbr \/\u003E\u003Cbr \/\u003E He is in legal practice as \"Certified ADR Practitioner-(CertADR)\" and was a Member of Ghana National Association of ADR Practitioners-MGNAAP,  a current Member of \u201cInternational Bar Association\u201d, and also a Member of International Law Association British Branch, with a 3rd PhD in International Commercial Law and Treaty. His other academic degrees includes, Master of Business Adminstration-MBA, Master of Public Health-MPH\/Master of Law-LLM, Bachelor of Law-LLB, Bachelor of Business Administration-BBA, Bachelor of Education in Psychology with minor in Law-BEd, and Post Graduate studies in Pastoral Ministry from Valley View University, Oyibi. \u003Cbr \/\u003E\u003Cbr \/\u003E Prof. Lowell is chartered and licensed as \"Accredited Management Consultant-AMG\u2122\" and also a Fellow and Global Academic Adviser and Board of Standard in Ghana, for Global Board of Academics & Professors Advisory Council of GAFM\u2122 USA. \u003Cbr \/\u003E\u003Cbr \/\u003E He is also Co-founder\/Programmes Director of Chartered Institute of Educational Practitioners, Ghana. A newly registered Educational Professional Institution. \u003Cbr \/\u003E\u003Cbr \/\u003E He has academic and professional reputation both international and local. He was the 1st Graduate School Coordinator for Valley View University, Kumasi campus. VVU, the 1st Ghanaian Premier Private University."
    ],
    "mr-kingsley-kwaku-pinkrah" => [
        "Mr. Kingsley Kwaku Pinkrah",
        "Founding President and CEO",
        "Mr. Kingsley Kwaku Pinkrah is a multiple award-winning social entrepreneur, social activist, and business consultant. He is the Founding President and CEO of the Community and Entrepreneurial Development Initiative (CEDI Ghana) and the Chief of Party of the Entrepreneurship Jobs for All (E-Jobs4All) Project. Kingsley has served as the Director of Research, Innovation, and Entrepreneurship at the Data Link University, an advisory mentor for President Clinton's Global Initiative University, the Queen's Young Leaders Programme established by Her Majesty Queen Elizabeth in the UK, and the Young African Leaders Initiative established by the United States government. <br /> <br/> He has been awarded the 2017 Africa's Social Entrepreneur of the Year, the 40 Under 40 Most Influential and Outstanding Social Entrepreneur of the Year, the 30 Under 30 Award, the Young Professional Role Model Award, and many others because of his exemplary leadership and contribution to global development. Kingsley holds a Master of Business Administration (Distinction) from the Kwame Nkrumah University of Science and Technology."
    ],
    "dr-gabriel-eshun" => [
        "Prof. Gabriel Eshun",
        "Executive Member and PRO",
        "Prof. Gabriel Eshun (PhD, MBA and BSc). He holds BSc from Kwame Nkrumah University of Science and Technology (KNUST), MBA and PhD from University of Leicester, UK. He is a Senior Lecturer and the Coordinator for Tourism Programme in the Geography Department of the Kwame Nkrumah University of Science and Technology. He specializes in marketing, tourism, entrepreneurship, ecotourism and green issues in hotels. He is also a performing poet and a motivational speaker."
    ],
    "prof-bernard-forjwuor" => [
        "Prof. Bernard Forjwuor",
        "Executive Member",
        "\u003Cb\u003EAppointment\u003C\/b\u003E\u003Cbr\/\u003E - Lecturer at University of Notre Dome, United State of America \u003Cbr\/\u003E- Professor of Politics at Mount Holyoke College, South Hadley, Massachusetts, USA \u003Cbr\/\u003E- Consortium for Faculty Diversity (CFD) Postdoctoral Fellow in Politics, July 2015.\u003Cbr\/\u003E\u003Cbr\/\u003E \u003Cb\u003EEducation\u003C\/b\u003E\u003Cbr\/\u003E Northwestern University, Evanston, Illinois USA - Ph.D. African American Studies, December 2015 \u003Cbr\/\u003E - Graduate Certificate in Critical Theory, June 2013 Ohio University, Athens, Ohio USA \u003Cbr\/\u003E - M.A. Political Science, June 2009 \u003Cbr\/\u003E - M. A. African Studies, March 2008 University of Guelph, Guelph, Ontario Canada. \u003Cbr\/\u003E - M. A. Theatr Studies, June 2005 University of Ghana, Legon, Accra Ghana \u003Cbr\/\u003E - B.A. Theatre Studies (Major) and English (Minor) May 2001"
    ],
    "prof-jose-mella-marquaz" => [
        "Prof. Jose Mella Marquaz",
        "Executive Member",
        "Prof. Jose Mella Marquaz (PhD, MBA and BA). Qualifications \u003Cbr\/\u003E - 1973: B.A. in Economics and Business Administration at UAM \u003Cbr\/\u003E - 1982: PhD (with distinction) in Economic Development at UAM. Thesis title: \u201cAn Economic\r\n Strategy for the Development of Underdeveloped Regions. The case of Galician Region\u201d. - 1987-1992: Associate Professor in\r\n Economic Development \u003Cbr\/\u003E- 1993-2015: Full Professor in Economic Development \u003Cbr\/\u003E- 1994-2015: Jean Monnet Professor appointed by the European Union (EU) for teaching Development Policy of the EU \u003Cbr\/\u003E \u003Cbr\/\u003E \u003Cb\u003ECurrent posts\u003C\/b\u003E \u003Cbr\/\u003E- Professor of Economics at Spiritan University College - Ejisu-Kumasi \u003Cbr\/\u003E- Full Professor of Economic Development (African countries) \u003Cbr\/\u003E- Member of the Faculty Council \u003Cbr\/\u003E-Jean Monnet Professor appointed by the EU Commission \u003Cbr\/\u003E- Evaluator of the EU Commission \u003Cbr\/\u003E- Program Director, International Economic Cooperation Program of Tangier-Tetouan University (Morocco) and Autonomous University of Madrid (Spain) \u003Cbr\/\u003E- Program Director, International Economic Cooperation Program of Oruro University (Bolivia) and Autonomous University of Madrid (Spain)"
    ],
    "prof-samuel-adu-prah" => [
        "Prof. Samuel Adu-Prah",
        "Advisor",
        "Prof. Samuel Adu-Prah is a professor of geography and geographic information science in the Department of Geography and Geology at Sam Houston State University (Texas, U.S.A.). He earned his degrees from the University of Ghana, Legon- Ghana [B.A (Hons)], University of Cambridge-United Kingdom (MPhil.), Alcorn State University, Mississippi (M.S), and Southern Illinois University (Ph.D.). His articles have appeared in such journals as \u003Ci\u003EApplied Geography, International Journal of Geographic Informatio and Geovisualization, African Geographical Review, GeoJournal, International Journal of Applied Geospatial Research, Forest Ecology and Management\u003C\/i\u003E, and others. \u003Cbr\/\u003E\u003Cbr\/\u003E Prof. Adu-Prah was a contributing author to the following books - \u003Ci\u003EUnderstanding a Changing World, ABC-CLIO (2014)\u003C\/i\u003E and \u003Ci\u003EEncyclopedia of Organic, Sustainable and Local Food (2009)\u003C\/i\u003E. He is a recent fellow (alumni) of the Carnegie African Diaspora Fellowship Program. He is a voting member of the American Association of Geographers (AAG) and Secretary to the African Specialty Group of the AAG. Prof. Adu-Prah is the coEditor-in-Chief of the International Journal of Applied Geospatial Research."
    ]
];